plugins:
  chat_integration_enabled:
    default: false
  chat_integration_discourse_username:
    default: system
    type: username
  chat_integration_delay_seconds:
    default: 20

#######################################
########## SLACK SETTINGS #############
#######################################
  chat_integration_slack_enabled:
    default: false
    validator: "ChatIntegrationSlackEnabledSettingValidator"
  chat_integration_slack_outbound_webhook_url:
    default: ''
    regex: '^https:\/\/hooks\.slack\.com\/services\/.+$'
  chat_integration_slack_excerpt_length:
    default: 400
  chat_integration_slack_icon_url:
    default: ''
  chat_integration_slack_incoming_webhook_token:
    default: ''
  chat_integration_slack_access_token:
    default: ''

#######################################
######### TELEGRAM SETTINGS ###########
#######################################
  chat_integration_telegram_enabled:
    default: false
  chat_integration_telegram_access_token:
    default: ''
  chat_integration_telegram_excerpt_length:
    default: 400
  chat_integration_telegram_enable_slash_commands:
    default: true
  chat_integration_telegram_secret:
    hidden: true

#######################################
########## DISCORD SETTINGS ###########
#######################################
  chat_integration_discord_enabled:
    default: false
  chat_integration_discord_excerpt_length:
    default: 400